version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build & Push Docker image
          command: |
            set -euo pipefail
            TAG="build-$CIRCLE_BUILD_NUM"
            echo "TAG=$TAG"
            docker build -t "buraksefil17/todo-app:$TAG" .
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push "buraksefil17/todo-app:$TAG"

  update_manifest:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      # manifest güncellemesi için docker gerekmiyor; setup_remote_docker kaldırıldı
      - run:
          name: Update kube_manifest with new image tag
          command: |
            set -euo pipefail

            TAG="build-$CIRCLE_BUILD_NUM"
            echo "Using TAG=$TAG"

            # Repo'yu token ile klonlamak yerine public read ile klonla, push öncesi remote'u token'lı yap
            git clone https://github.com/buraksefil/kube_manifest.git
            cd kube_manifest

            git config user.email "buraksefil@yahoo.com"
            git config user.name "buraksefil"

            # Manifest'teki image satırını tek seferde DOĞRU repo + tag ile güncelle
            # Yalnızca todo-app image'ını hedefleyen güvenli bir regex:
            sed -E -i 's|^( *image: *)(buraksefil17?/todo-app:.*)$|\1buraksefil17/todo-app:'"$TAG"'|' manifest/deployment.yaml

            echo "Updated manifest:"
            cat manifest/deployment.yaml

            # Değişiklik var mı kontrol et; yoksa clean exit
            if git diff --quiet; then
              echo "No changes in manifest (already at $TAG). Skipping commit/push."
              exit 0
            fi

            git add manifest/deployment.yaml
            git commit -m "chore: bump image to buraksefil17/todo-app:${TAG}"

            # Push için token'lı remote kullan (username:token formatı)
            git remote set-url origin "https://${GITHUB_USERNAME}:${GITHUB_PERSONAL_TOKEN}@github.com/buraksefil/kube_manifest.git"
            git push origin main -q

workflows:
  GitOpsflow:
    jobs:
      - build_and_push
      - update_manifest:
          requires:
            - build_and_push
